story4/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story4app.urls')),
]

story4app/urls.py
from django.urls import path
from . import views

app_name = 'story4app'

urlpatterns = [
    path('', views.home, name='home'),
    path('aboutme/', views.aboutme, name='aboutme'),
    # dilanjutkan ...
]

story4app/models.py
from django.db import models

# Create your models here.

story4app/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def aboutme(request):
    return render(request, 'aboutme.html')

# Create your views here.

story4app/templates/aboutme.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Nicolas' Personal Blog</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="{% static 'css/story4.css' %}">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    
  </head>
  <body>
    <div class="container">
  <div class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand motto" href="#">Live Your Life</a><button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarColor01" style="">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'story4app:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Blog</a>
          </li>
          <li class="nav-item">
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'story4app:aboutme' %}".html"">About Me</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Connect!</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>

  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark utama1">
    <div class="container">
      <div class="row justify-content-center font-weight-bold profilejudul">
        PROFILE
      </div>
      <div class="row align-items-center inforow">
        <div class="col align-items-center mycol">
          <img src="{% static 'pic/name.png' %}" class="img-fluid icons" alt="Responsive image">  
        </div>  
        <div class="col-5 info"> 
          Nicolas Henry Wijaya
        </div>
        <div class="col mycol">
          <img src="{% static 'pic/age.png' %}" class="img-fluid icons" alt="Responsive image">
        </div>
        <div class="col-5 info"> 
          March 29th 2000
        </div>
      </div>  
      <div class="row align-items-center inforow">
        <div class="col mycol">
          <img src="{% static 'pic/home.png' %}" class="img-fluid icons" alt="Responsive image">  
        </div>
        <div class="col-5 info"> 
          Bahagia St., West Jakarta
        </div>
        <div class="col mycol">
          <img src="{% static 'pic/blood.png' %}" class="img-fluid icons" alt="Responsive image">
        </div>
        <div class="col-5 info"> 
          O Positive
        </div>
      </div>
    </div>
  </div>

  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark utama2">
    <div class="container">
      <div class="row justify-content-center font-weight-bold profilejudul">
        EXPERIENCES
      </div>
      <div class="row align-items-center inforow">
        <div class="col-2 mycol2">
          <img src="{% static 'pic/uiaw.png' %}" class="img-fluid icons2" alt="Responsive image">  
        </div>  
        <div class="col info"> 
          <strong> 7th UI Art War</strong> </br> Staff of Equipments
        </div>
        <div class="col-2 mycol2">
          <img src="{% static 'pic/cgt.png' %}" class="img-fluid icons2" alt="Responsive image">
        </div>
        <div class="col info"> 
          <strong>CGT In Action</strong></br> Staff of Public Relations
        </div>
      </div>  
      <div class="row align-items-center inforow">
        <div class="col-2 mycol2">
          <img src="{% static 'pic/kmk.png' %}" class="img-fluid icons2" alt="Responsive image">  
        </div>
        <div class="col info"> 
          <strong>Presidium KMK UI 2019</strong></br> Staff of HRD
        </div>
        <div class="col-2 mycol2">
          <img src="{% static 'pic/compfest.png' %}" class="img-fluid icons2" alt="Responsive image">
        </div>
        <div class="col info"> 
          <strong>COMPFEST 12</strong></br> Staff of Digital Marketing
        </div>
      </div>
    </div>
  </div>

  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark utama3">
    <div class="container">
      <div class="row justify-content-center font-weight-bold profilejudul">
        SKILLS
      </div>
     <p>Python</p>
      <div class="containers">
        <div class="skills python">80%</div>
      </div>

      <p>Java</p>
      <div class="containers">
        <div class="skills java">90%</div>
      </div>

      <p>Photoshop</p>
      <div class="containers">
        <div class="skills photoshop">65%</div>
      </div>

      <p>HTML</p>
      <div class="containers">
        <div class="skills HTML">50%</div>
      </div> 
    </div>
  </div>

  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark utama2">
    <div class="container">
      <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
    </div>
  </div>

  
</div>


</body>
</html>

story4app/templates/home.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Nicolas' Personal Blog</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/blog/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="{% static 'css/story4.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    
  </head>
  <body>
    <div class="container">
  <div class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      
      <a class="navbar-brand motto" href="#">Live Your Life</a><button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse navatas" id="navbarColor01" style="">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'story4app:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Blog</a>
          </li>
          <li class="nav-item">

          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'story4app:aboutme' %}">About Me</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Connect!</a>
          </li>
        </ul>
      </div>
    </nav>
  </div>



  <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark utama">
    <div class="row mb-2 align-items-center utamakonten">
      <div class="col-md-6">
        <h1 class="display-4 font-italic">Hi There!</h1>
        <p class="lead my-3">I'm just an ordinary boy who loves musics, films, and books. As the only child, i often 
        spend my leisure times alone with my gadgets or books, and that's make me a dominant introvert.
        Oh! I am a big fan of kpop too!</p>
      </div>
      <div class="col-md-6" >
        <img src="{% static 'pic/cropped.png' %}" class="rounded float-right foto" alt="...">
      </div>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">Small peeps don't do balls</h3>
          <div class="mb-1 text-muted">29 Sept</div>
          <p class="card-text mb-auto">Dari sekian banyak olahraga yang ada di dunia ini, salah satu yang paling ...</p>
          <a href="#" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img class="bd-placeholder-img" width="200" height="150" xmlns="http://www.w3.org/2000/svg" src="{% static 'pic/basket.png' %}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <h3 class="mb-0">Music is Lyfe!</h3>
          <div class="mb-1 text-muted">30 Sept</div>
          <p class="mb-auto">Musik seringkali saya pilih untuk menemani di berbagai situasi. Terlebih ketika saya berada di tempat kos ...</p>
          <a href="#" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img class="bd-placeholder-img" width="200" height="150" xmlns="http://www.w3.org/2000/svg" src="{% static 'pic/music.png' %}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>